/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_twodee_madeup_Bridge */

#ifndef _Included_org_twodee_madeup_Bridge
#define _Included_org_twodee_madeup_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onDraw
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    resetView
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_resetView
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    disconnectFaces
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_disconnectFaces
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onInitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onSizeChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onSizeChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onLeftMouseUp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onLeftMouseUp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onLeftMouseDown
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onLeftMouseDown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    onLeftMouseDragged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_onLeftMouseDragged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    cullFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_cullFront
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    cullBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_cullBack
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    cullNone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_cullNone
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    setOutPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_setOutPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    setGeometryMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_setGeometryMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    enterProgram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_enterProgram
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitProgram
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitProgram
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    enterBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_enterBlock
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitBlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitBlock
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    enterCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_enterCall
  (JNIEnv *, jclass);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitIntegerLiteral
 * Signature: (IIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitIntegerLiteral
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDecimalLiteral
 * Signature: (FIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDecimalLiteral
  (JNIEnv *, jclass, jfloat, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitBooleanLiteral
 * Signature: (ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitBooleanLiteral
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitStringLiteral
 * Signature: (Ljava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitStringLiteral
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitNegation
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitNegation
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitArrayLiteral
 * Signature: (IIIILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitArrayLiteral
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring, jint);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitArrayLength
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitArrayLength
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitArraySubscript
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitArraySubscript
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitStatement
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitStatement
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitRepeat
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitRepeat
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitIf
 * Signature: (IIIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitIf
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitIfOneLiner
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitIfOneLiner
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitWhile
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitWhile
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDefineFunction
 * Signature: (Ljava/lang/String;[Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDefineFunction
  (JNIEnv *, jclass, jstring, jobjectArray, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDefineVariable
 * Signature: (Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDefineVariable
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDefineArrayElement
 * Signature: (ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDefineArrayElement
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitCall
 * Signature: (Ljava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitCall__Ljava_lang_String_2IIIILjava_lang_String_2
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitCall
 * Signature: (Ljava/lang/String;[Ljava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitCall__Ljava_lang_String_2_3Ljava_lang_String_2IIIILjava_lang_String_2
  (JNIEnv *, jclass, jstring, jobjectArray, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitAdd
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitAdd
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitSubtract
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitSubtract
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitMultiply
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitMultiply
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDivide
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDivide
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitDecimalDivide
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitDecimalDivide
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitRemainder
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitRemainder
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitAnd
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitAnd
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitOr
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitOr
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitNot
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitNot
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitLesser
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitLesser
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitLesserOrEqual
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitLesserOrEqual
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitGreater
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitGreater
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitGreaterOrEqual
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitGreaterOrEqual
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitEqual
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitEqual
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitNotEqual
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitNotEqual
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitForTo
 * Signature: (Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitForTo
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitForThrough
 * Signature: (Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitForThrough
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitForRange
 * Signature: (Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitForRange
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitForRangeBy
 * Signature: (Ljava/lang/String;ZIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitForRangeBy
  (JNIEnv *, jclass, jstring, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitPower
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitPower
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     org_twodee_madeup_Bridge
 * Method:    exitAbsoluteValue
 * Signature: (IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_twodee_madeup_Bridge_exitAbsoluteValue
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
